version: '3.8'

services:
  app:
    build: .
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - chatbot_data:/app/data
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: chatbot-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  chatbot_data:
  mongo_data: 